-- 코드를 입력하세요
SELECT B.TITLE, BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R USING(BOARD_ID)
WHERE EXTRACT(YEAR_MONTH FROM B.CREATED_DATE) = '202210'
ORDER BY CREATED_DATE, B.TITLE;
